### ISSUE TITLE
Document XMBC

### ISSUE THREAD

**Issue by domenic** [w3c-webmob/wake-lock-use-cases#3] opened 2014-06-17 20:55 UTC
https://twitter.com/EINS78/status/479001526233743360

I bet most media gallery apps do the same thing. (Plex, XMBC, Boxee, Windows Media Center, Front Row, ...)

**Comment by marcoscaceres** [comment] 2014-07-09 15:37
Duplicate of #5

**Closed as completed by marcoscaceres** 2014-07-09 15:37 UTC

**Comment by marcoscaceres** [comment] 2014-07-09 15:39
I'm going to add the fullscreen aspect as a requirement. That is, a browser might only support this functionality if the application is running in fullscreen.
